server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Black273150@tcp(172.18.0.2:3306)/shop
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_secret: "secret"
  expire_duration: 360000s
  host: smtp.qq.com
  port: 587
  username: 1737429543@qq.com
  password: vrescmcdciqnfbjf
  isssl: true